name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # 仅生成一个简单的 GIF 来进行调试
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: wangzaiwang-hub
          outputs: dist/github-snake.gif?color_snake=green

      # 推送文件
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
