    name: Generate Snake Animation

    on:
      schedule:
        - cron: "0 */12 * * *" # Runs every 12 hours
      workflow_dispatch: # Allows manual triggering

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2

          # Generates the snake SVG and customizes the colors
          - uses: Platane/snk@v3
            id: snake-gif
            with:
              github_user_name: wangzaiwang-hub
              # Your theme colors are used here
              outputs: |
                dist/github-snake-dark.svg?palette=github-dark&color_snake=00fff0&color_dots=ff00cc
                dist/github-snake-light.svg?palette=github-light&color_snake=ff00cc&color_dots=00fff0

          # Pushes the generated files to the 'output' branch
          - uses: crazy-max/ghaction-github-pages@v3
            with:
              target_branch: output
              build_dir: dist
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
