name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # 每 12 小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 关键：授予内容写入权限
    steps:
      - uses: actions/checkout@v4 # 更新到 v4

      # 生成贪吃蛇 SVG 并自定义颜色
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: wangzaiwang-hub
          # 在这里使用你的主题颜色
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark&color_snake=00fff0&color_dots=ff00cc
            dist/github-snake-light.svg?palette=github-light&color_snake=ff00cc&color_dots=00fff0

      # 将生成的文件推送到 'output' 分支
      - uses: crazy-max/ghaction-github-pages@v4 # 更新到 v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
